eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eurekaclient
